### ISSUE TITLE
Speed bar flickers when maxed out

### ISSUE THREAD

**Issue by KronosVoid** [hibiii/BoatHud#10]
When moving at the fastest speed the speed bar can display, it starts to flicker between showing no speed and max speed quickly.

**Comment by hibiii** [comment]
The flickering is intended, it's intended to mimic real shift lights indicating you're redlining the engine. Since boats don't have gearshifts, RPM, or even motors for that matter, I've repurposed the light bar for speed, hence the different light bar modes, they represent different speeds in "standard" block configurations. If you go at blue ice speeds but the light bar is configured for packed ice, then you're "overspeeding" it, and it'll blink indicating that you're going too fast for it to display.

**Comment by KronosVoid** [comment]
That makes sense, thank you for the reply! I'd already thought it'd be weird to have such a thing go unnoticed but I figured it also wouldn't hurt to report it.
