### ISSUE TITLE
Horse version  ?

### ISSUE THREAD

**Issue by JamesDAdams** [hibiii/BoatHud#8]
Hi,

thanks for your mod ! An horse version is planned ? :)

Thanks.

**Comment by hibiii** [comment]
There has never been any plans for horse support, no. I don't mean to sound like a takedown, but what would a horse HUD even display? There's no drifting because the controls are immediately responsive, horses accelerate and decelerate very quickly, speed could be there but that's such a generic thing to track, player name and ping? Sure, that could be the BoatHud signature.

The speed bar would be a funny one: there's absolutely no benefit for running horses across different surfaces, not even stairs and foot paths (at high enough speeds, the server gets confused on how you're moving and thinks you're cheating). For the boat "version", it's there because boats on ice are much more difficult to control than on water, and the ice gives them a speed boost. The speed bar helps the player judge how fast they're going by visualizing said speed, but on a horse, you can just let go of W to stop. Not to mention, what would be the upper limit of the speed bar? The fastest horse speed available in vanilla survival? Or the top speed of the horse?

Inputs are also interesting because you _need_ mouse to steer a horse, but mouse inputs are not easy to transform into a small HUD element while also keeping precision.

I could add the name of the horse and how full a donkey's or a mule's inventory is, but last time I tried to do it with chestboats, it was nontrivial. I'll have to investigate how it is now and if it's changed in the 20.3 snapshots because who knows what might happen xd very large undocumented changes are good to keep the game healthy xd!.

If you have any ideas, let me know, I'd love to hear them.
